[package]
name = "axum-blog"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true

[dependencies]
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["full"] }
